//export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
//export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
//export const GET_CART_DATA_ERROR = "GET_CART_DATA_ERROR";

export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
export const ADD_CART_ITEM__ERROR = "ADD_CART_ITEM__ERROR";



export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM__ERROR = "DELETE_CART_ITEM__ERROR";

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM__ERROR = "UPDATE_CART_ITEM__ERROR";

